Update ci-cd.yml -> new job : deploy-render

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -73,7 +73,7 @@ jobs:
           name: coverage-report
           path: htmlcov
 
-  deploy:
+  deploy-docker:
     runs-on: ubuntu-latest
     needs: build  # Attend la fin du job 'build' avant de démarrer
     
@@ -102,7 +102,7 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Étape 4: Get short SHA for tagging
+      # Étape 4: Get short SHA
       - name: Get short SHA
         id: vars
         run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
@@ -119,3 +119,36 @@ jobs:
             docker push $IMAGE_NAME:$SHORT_SHA
             docker pull $IMAGE_NAME:$SHORT_SHA
           done
+
+  deploy-render:
+    runs-on: ubuntu-latest
+    needs: deploy-docker
+    if: github.ref == 'refs/heads/master'
+    steps:
+
+      # Étape 1: Recovers source code with sub-modules
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+          ref: ${{ github.ref }}  # Récupère la référence de la branche ou du commit
+
+      # Étape 2: Get short SHA
+      - name: Get short SHA
+        id: vars
+        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+
+      # Étape 3: Déploiement avec un webhook Render verifie le status 200 de la requete
+      - name: Deploy to Render
+        env:
+          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
+          sha_short: ${{ env.SHA_SHORT }}
+        run: |
+
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${deploy_url}&ref=${sha_short}")
+          if [ "${HTTP_STATUS}" -eq 200 ]; then
+            echo "Deployment successful. Status: ${HTTP_STATUS}"
+          else
+            echo "Deployment failed. Status: ${HTTP_STATUS}"
+            exit 1
+          fi
